(()=>{
const S={src:'',safe:'',name:'',regions:[],method:'auto',models:{ocr:null,face:null,coco:null,tf:false},running:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function toast(t){const e=$('#toast');e.textContent=t;e.style.display='block';clearTimeout(window.__tt);window.__tt=setTimeout(()=>e.style.display='none',2600)}
function page(n){$$('.page').forEach(x=>x.classList.toggle('on',x.dataset.page===n));$$('.bottom button').forEach(x=>x.classList.toggle('on',x.dataset.nav===n));window.scrollTo({top:0,behavior:'smooth'})}
function setStatus(p,t,s=''){ $('#progress').style.width=Math.round(p*100)+'%';$('#statusText').textContent=t;$('#statusSub').textContent=s||'กำลังประมวลผลด้วย AI ในอุปกรณ์ของคุณ' }
function loadScript(url){return new Promise((ok,no)=>{const s=document.createElement('script');s.src=url;s.async=true;s.onload=ok;s.onerror=()=>no(new Error('โหลดโมเดลไม่สำเร็จ'));document.head.appendChild(s)})}
async function loadAny(urls,test){if(test())return;let err;for(const u of urls){try{await loadScript(u);if(test())return}catch(e){err=e}}throw err||new Error('ไม่สามารถโหลดโมเดลได้')}
async function ensureModels(){const M=S.models,set=setStatus;let jobs=[];
 if(!M.ocr)jobs.push((async()=>{set(.08,'กำลังโหลด OCR','รองรับข้อความภาษาไทยและอังกฤษ');await loadAny(['https://cdn.jsdelivr.net/npm/tesseract.js@6/dist/tesseract.min.js','https://unpkg.com/tesseract.js@6/dist/tesseract.min.js'],()=>!!window.Tesseract);try{M.ocr=await Tesseract.createWorker(['eng','tha'],1,{logger:m=>set(.12+(m.progress||0)*.30,'กำลังโหลด OCR',`${m.status||'working'} ${Math.round((m.progress||0)*100)}%`)})}catch(e){M.ocr=await Tesseract.createWorker('eng')}})());
 if(!M.face&&'FaceDetector' in window){try{M.face={native:new FaceDetector({fastMode:true,maxDetectedFaces:30})}}catch{}}
 if(!M.face||!M.coco)jobs.push((async()=>{set(.12,'กำลังโหลด Vision AI','ตรวจใบหน้าและวัตถุในภาพ');await loadAny(['https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.22.0/dist/tf.min.js','https://unpkg.com/@tensorflow/tfjs@4.22.0/dist/tf.min.js'],()=>!!window.tf);if(!M.tf){try{await tf.setBackend('webgl')}catch{}await tf.ready();M.tf=true}
 if(!M.face){await loadAny(['https://cdn.jsdelivr.net/npm/@tensorflow-models/blazeface@0.1.0/dist/blazeface.js','https://unpkg.com/@tensorflow-models/blazeface@0.1.0/dist/blazeface.js'],()=>!!window.blazeface);M.face={blaze:await blazeface.load()}}
 if(!M.coco){await loadAny(['https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd@2.2.3/dist/coco-ssd.min.js','https://unpkg.com/@tensorflow-models/coco-ssd@2.2.3/dist/coco-ssd.min.js'],()=>!!window.cocoSsd);M.coco=await cocoSsd.load({base:'lite_mobilenet_v2'})}})());
 await Promise.allSettled(jobs);if(!M.ocr&&!M.face&&!M.coco)throw new Error('AI models โหลดไม่สำเร็จ กรุณาตรวจอินเทอร์เน็ตแล้วลองใหม่') }
function classify(text=''){const s=text.trim(),digits=(s.match(/\d/g)||[]).join('');const rules=[
 ['เลขประจำตัว/เลขบัตร',/\b\d{1}-?\d{4}-?\d{5}-?\d{2}-?\d\b|\b\d{3}-\d{2}-\d{4}\b|เลขบัตร|บัตรประชาชน|passport|national id|identity card/i,.99,'ID'],
 ['อีเมล',/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i,.98,'Email'],
 ['เบอร์โทรศัพท์',/(?:\+?\d[\d\s().-]{7,}\d)/,.96,'Phone'],
 ['ที่อยู่/ตำแหน่ง',/\b(?:address|street|road|district|province|postcode|latitude|longitude|gps|bangkok|thailand)\b|ที่อยู่|ถนน|แขวง|เขต|อำเภอ|จังหวัด|พิกัด|กรุงเทพ|ประเทศไทย/i,.84,'Address'],
 ['บัญชีออนไลน์',/(?:https?:\/\/|www\.)\S+|@[a-z0-9_]{3,}/i,.84,'Account']];
 for(const r of rules)if(r[1].test(s))return{yes:true,label:r[0],score:r[2],kind:r[3]};if(digits.length===13||digits.length>=15)return{yes:true,label:'เลขระบุตัวบุคคล',score:.92,kind:'ID'};return{yes:false}}
function mk(label,kind,score,b,w,h,source,evidence=''){let[x,y,bw,bh]=b,px=Math.max(4,bw*.05),py=Math.max(4,bh*.12),x0=clamp(x-px,0,w),y0=clamp(y-py,0,h),x1=clamp(x+bw+px,0,w),y1=clamp(y+bh+py,0,h);return{id:Math.random(),label,kind,score,x:x0/w,y:y0/h,w:(x1-x0)/w,h:(y1-y0)/h,source,evidence}}
function lines(d){let out=[];if(Array.isArray(d?.lines))out.push(...d.lines);for(const b of d?.blocks||[])for(const p of b.paragraphs||[])for(const l of p.lines||[])out.push(l);if(!out.length&&Array.isArray(d?.words))out.push(...d.words);return out}
async function analyze(img){await ensureModels();const M=S.models,w=img.naturalWidth,h=img.naturalHeight,rs=[];setStatus(.55,'กำลังตรวจใบหน้า','Face & identity detection');
 const fp=(async()=>{if(M.face?.native){try{const fs=await M.face.native.detect(img);for(const f of fs){const b=f.boundingBox;rs.push(mk('ใบหน้า','Face',.96,[b.x,b.y,b.width,b.height],w,h,'FaceDetector'))}return}catch{}}
 if(M.face?.blaze){const fs=await M.face.blaze.estimateFaces(img,false);for(const f of fs){const a=f.topLeft,b=f.bottomRight,sc=Array.isArray(f.probability)?f.probability[0]:(f.probability||.9);rs.push(mk('ใบหน้า','Face',Math.max(.82,sc),[a[0],a[1],b[0]-a[0],b[1]-a[1]],w,h,'BlazeFace'))}}})();
 setStatus(.65,'กำลังอ่านข้อความ','ค้นหา PII / PDPA');const op=M.coco?M.coco.detect(img,30,.35).catch(()=>[]):Promise.resolve([]),oc=M.ocr?M.ocr.recognize(img,{rotateAuto:true},{blocks:true,text:true,words:true}).catch(()=>null):Promise.resolve(null);const[_,objects,ocr]=await Promise.all([fp,op,oc]);
 if(ocr?.data){for(const l of lines(ocr.data)){const c=classify(l.text||'');if(c.yes&&l.bbox){const b=l.bbox;rs.push(mk(c.label,c.kind,c.score,[b.x0,b.y0,b.x1-b.x0,b.y1-b.y0],w,h,'OCR',(l.text||'').trim().slice(0,60)))}}}
 for(const o of objects||[]){if(['laptop','tv','cell phone','book'].includes(o.class)){rs.push(mk(o.class==='cell phone'?'หน้าจอโทรศัพท์':'หน้าจอ/เอกสาร','Screen',Math.max(.60,o.score*.80),o.bbox,w,h,'COCO-SSD',o.class))}}
 rs.sort((a,b)=>b.score-a.score);setStatus(1,'ตรวจเสร็จแล้ว',rs.length?`พบ ${rs.length} จุดที่ควรปกป้อง`:'ไม่พบข้อมูลส่วนบุคคลชัดเจน');return rs}
function icon(kind){return kind==='Face'?'◉':kind==='Phone'?'☎':kind==='Email'?'@':kind==='ID'?'▤':kind==='Address'?'⌖':kind==='Screen'?'▣':'•'}
function render(){const list=$('#detectList'),ov=$('#overlay');list.innerHTML='';ov.innerHTML='';if(!S.regions.length){list.innerHTML='<div class="empty">ไม่พบข้อมูลส่วนบุคคลที่ชัดเจนในภาพนี้</div>';$('#riskLabel').textContent='ไม่พบความเสี่ยงชัดเจน';return}
 $('#riskLabel').textContent=`พบ ${S.regions.length} จุด`;for(const [i,r] of S.regions.entries()){const row=document.createElement('div');row.className='row';row.innerHTML=`<div class="rowIcon">${icon(r.kind)}</div><div><b>${r.label}</b><small>${r.evidence||r.source}</small></div><span class="score">${Math.round(r.score*100)}%</span>`;list.appendChild(row)};drawOverlay()}
function drawOverlay(){const ov=$('#overlay'),im=$('#sourceImg'),stage=$('#photoStage').getBoundingClientRect();ov.innerHTML='';if(!im.naturalWidth)return;const ar=im.naturalWidth/im.naturalHeight;let dw=stage.width,dh=dw/ar;if(dh>stage.height){dh=stage.height;dw=dh*ar}const ox=(stage.width-dw)/2,oy=(stage.height-dh)/2;for(const r of S.regions){const d=document.createElement('div');d.className='box';d.style.cssText=`left:${ox+r.x*dw}px;top:${oy+r.y*dh}px;width:${r.w*dw}px;height:${r.h*dh}px`;d.innerHTML=`<label>${r.label}</label>`;ov.appendChild(d)}}
async function runScan(){if(!S.src)return toast('กรุณาเลือกรูปก่อน');if(S.running)return;S.running=true;$('#rescanBtn').disabled=true;setStatus(.02,'กำลังเริ่ม AI','ครั้งแรกอาจใช้เวลาสักครู่เพื่อโหลดโมเดล');try{const im=new Image();im.src=S.src;await new Promise((ok,no)=>{im.onload=ok;im.onerror=no});S.regions=await analyze(im);render();toast(S.regions.length?`พบ ${S.regions.length} จุดที่ควรปกป้อง`:'ไม่พบข้อมูลส่วนบุคคลชัดเจน')}catch(e){console.error(e);setStatus(0,'AI ยังไม่พร้อม',e.message);toast(e.message)}finally{S.running=false;$('#rescanBtn').disabled=false}}
function protect(){if(!S.src)return toast('กรุณาเลือกรูปก่อน');if(!S.regions.length)return toast('ยังไม่มีจุดให้ปกป้อง กรุณาเริ่มตรวจด้วย AI ก่อน');$('#working').classList.add('on');const im=new Image();im.src=S.src;im.onload=()=>{const c=$('#canvas'),scale=Math.min(1,1800/Math.max(im.naturalWidth,im.naturalHeight));c.width=Math.round(im.naturalWidth*scale);c.height=Math.round(im.naturalHeight*scale);const x=c.getContext('2d');x.drawImage(im,0,0,c.width,c.height);for(const r of S.regions){const X=r.x*c.width,Y=r.y*c.height,W=r.w*c.width,H=r.h*c.height;let m=S.method;if(m==='auto')m=(['Phone','Email','ID','Address','Account'].includes(r.kind)?'redact':r.kind==='Face'?'pixelate':'blur');if(m==='redact'){x.fillStyle='#e9eaec';x.fillRect(X,Y,W,H)}else if(m==='pixelate'){const t=document.createElement('canvas');t.width=Math.max(3,Math.round(W/15));t.height=Math.max(3,Math.round(H/15));const q=t.getContext('2d');q.drawImage(c,X,Y,W,H,0,0,t.width,t.height);x.save();x.imageSmoothingEnabled=false;x.drawImage(t,0,0,t.width,t.height,X,Y,W,H);x.restore()}else{const t=document.createElement('canvas');t.width=Math.max(1,Math.round(W));t.height=Math.max(1,Math.round(H));const q=t.getContext('2d');q.filter='blur(26px)';q.drawImage(c,X,Y,W,H,0,0,t.width,t.height);x.drawImage(t,X,Y,W,H)}}S.safe=c.toDataURL('image/jpeg',.94);$('#resultImg').src=S.safe;$('#protectedCount').textContent=`${S.regions.length} จุด`;$('#methodLabel').textContent=S.method==='auto'?'AI Auto':S.method==='blur'?'เบลอ':S.method==='pixelate'?'พิกเซล':'ปิดทึบ';setTimeout(()=>{$('#working').classList.remove('on');page('result')},350)}}
function loadFile(f){if(!f||!f.type.startsWith('image/'))return;const rd=new FileReader();rd.onload=()=>{S.src=rd.result;S.safe='';S.name=f.name;S.regions=[];$('#sourceImg').src=S.src;$('#fileName').textContent=f.name;setStatus(0,'พร้อมตรวจ','กด “เริ่มตรวจด้วย AI”');$('#detectList').innerHTML='<div class="empty">กด “เริ่มตรวจด้วย AI” เพื่อวิเคราะห์ภาพนี้</div>';$('#riskLabel').textContent='ยังไม่ได้ตรวจ';$('#overlay').innerHTML='';page('scan')};rd.readAsDataURL(f)}
function save(){if(!S.safe)return;const a=document.createElement('a');a.href=S.safe;a.download='blindspot-safe-'+(S.name||'photo.jpg').replace(/\.[^.]+$/,'.jpg');a.click()}
async function share(){if(!S.safe)return;try{const blob=await (await fetch(S.safe)).blob();const file=new File([blob],'blindspot-safe.jpg',{type:'image/jpeg'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'BlindSpot AI'})}else save()}catch{save()}}
$('#pickBtn').addEventListener('click',()=>$('#fileInput').click());$('#fileInput').addEventListener('change',e=>loadFile(e.target.files?.[0]));$('#backHome').addEventListener('click',()=>page('home'));$('#rescanBtn').addEventListener('click',runScan);$('#protectBtn').addEventListener('click',protect);$('#saveBtn').addEventListener('click',save);$('#shareBtn').addEventListener('click',share);$('#againBtn').addEventListener('click',()=>{$('#fileInput').value='';page('home')});$$('.chip').forEach(b=>b.addEventListener('click',()=>{$$('.chip').forEach(x=>x.classList.remove('on'));b.classList.add('on');S.method=b.dataset.method}));$$('.compareTabs button').forEach(b=>b.addEventListener('click',()=>{$$('.compareTabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('#resultImg').src=b.dataset.view==='safe'?S.safe:S.src}));$$('.bottom button').forEach(b=>b.addEventListener('click',()=>{const n=b.dataset.nav;if(n==='scan'&&!S.src){$('#fileInput').click();return}page(n)}));window.addEventListener('resize',()=>{if(document.querySelector('[data-page="scan"]').classList.contains('on'))drawOverlay()});
})();